FROM ubuntu
MAINTAINER crsnplusplus <crsnplusplus@gmail.com>

RUN apt-get update

RUN apt-get install -y apt-utils vim curl apache2 apache2-utils install git-core

RUN apt-get install -y python3
RUN ln /usr/bin/python3 /usr/bin/python

RUN apt-get install -y python3-pip
RUN ln /usr/bin/pip3 /usr/bin/pip

RUN apt-get install -y python3-matplotlib

RUN apt-get install -y libfreetype6-dev libpng12-dev language-pack-en

RUN pip install --upgrade pip
RUN pip install ptvsd

RUN rm -rf /var/lib/apt/lists/*

WORKDIR /home/projects/

RUN git clone -b development/structure https://github.com/crsnplusplus/bartez.git

WORKDIR /home/projects/bartez/
RUN python setup.py develop

EXPOSE 3500
